### ISSUE TITLE
rfid-d10x python code eventually stops being able to read

### ISSUE THREAD

**Issue by SvenDowideit** [FollyEngine/1819#11]
note: `thereisnofunction` exception is currently an intentional goto

normal resets look like:

```
160
type == 0xa0
length == 19 (0x13)
READ: address = 0x01 data == 0x89183400300833b2ddd901400000000042
read : 0x89183400300833b2ddd901400000000042
160
type == 0xa0
length == 10 (0xa)
READ: address = 0x01 data == 0x8900000800000072
read : 0x8900000800000072
Traceback (most recent call last):
  File "./rfid-d10x/main.py", line 283, in <module>
    thereisnofunction()
NameError: name 'thereisnofunction' is not defined
Send Reset
crc: 0xec
bytearray(b'\xa0\x03\x01p\xec')
------------------------------------- cmd_real_time_inventory
data: ff
crc: 0xd3
bytearray(b'\xa0\x04\x01\x89\xff\xd3')
160
type == 0xa0
length == 19 (0x13)
READ: address = 0x01 data == 0x89303400300833b2ddd901400000000045
read : 0x89303400300833b2ddd901400000000045
160
type == 0xa0

```

at the end, we get

```
length == 19 (0x13)
READ: address = 0x01 data == 0x89303400300833b2ddd901400000000046
read : 0x89303400300833b2ddd901400000000046
160
type == 0xa0
length == 19 (0x13)
READ: address = 0x01 data == 0x89303400300833b2ddd901400000000040
read : 0x89303400300833b2ddd901400000000040
160
type == 0xa0
length == 10 (0xa)
READ: address = 0x01 data == 0x8900000a00000094
read : 0x8900000a00000094
Traceback (most recent call last):
  File "./rfid-d10x/main.py", line 283, in <module>
    thereisnofunction()
NameError: name 'thereisnofunction' is not defined
Send Reset
crc: 0xec
bytearray(b'\xa0\x03\x01p\xec')
------------------------------------- cmd_real_time_inventory
data: ff
crc: 0xd3
bytearray(b'\xa0\x04\x01\x89\xff\xd3')
crc: 0xea
bytearray(b'\xa0\x03\x01r\xea')
160
type == 0xa0
length == 10 (0xa)
READ: address = 0x01 data == 0x8900000000000000
crc: 0xe5
bytearray(b'\xa0\x03\x01w\xe5')
```

**Comment by SvenDowideit** [comment]
I've done some things to make it take alot longer to happen - but it still happens eventually :(
