### ISSUE TITLE
rfid-mifare has a crash

### ISSUE THREAD

**Issue by SvenDowideit** [FollyEngine/1819#12]
```
+Removed:  3B8F8001804F0CA000000306030001000000006A
+Inserted:  3B00
Traceback (most recent call last):
  File "//usr/lib/python3/dist-packages/smartcard/CardMonitoring.py", line 176, in run
    (addedcards, removedcards))
  File "//usr/lib/python3/dist-packages/smartcard/Observer.py", line 63, in notifyObservers
    observer.update(self, arg)
  File "./rfid-mifare/main.py", line 55, in update
    connection.connect( CardConnection.T1_protocol )
  File "//usr/lib/python3/dist-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "//usr/lib/python3/dist-packages/smartcard/pcsc/PCSCCardConnection.py", line 128, in connect
    SCardGetErrorMessage(hresult))
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T1. Card protocol mismatch.
retry:

```

**Comment by SvenDowideit** [comment]
this is probably python3 stuff - python2 worked for months
